include:
  - package:flutter_lints/flutter.yaml
  - package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/package/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
  plugins:
    - custom_lint
  errors:
    avoid_print: error
    public_member_api_docs: ignore
