openapi: 3.0.0
info:
  version: 1.0.0
  title: Swagger Petstore
paths:
  /pets:
    get:
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            maximum: 100
            format: int32
      responses:
        200:
          description: OK
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/Pets'
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Pets:
      type: array
      maxItems: 100
      items:
        $ref: '#/components/schemas/Pet'
