// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.masahikokobayashi.flutterlab.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object LocalNotificationPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}
private open class LocalNotificationPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}

/**
 * Pigeon host API for displaying local notifications on Android.
 *
 * Used to surface FCM messages received while the app is in the
 * foreground, since Android does not display them automatically.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface LocalNotificationHostApi {
  /**
   * Shows a notification in the system tray with the given [title]
   * and [body].
   *
   * [payload] is an opaque key/value bag (typically the FCM data
   * payload) attached to the tap intent so it can be delivered back
   * to Dart when the user taps the notification.
   */
  fun show(title: String, body: String, payload: Map<String, String>)
  /**
   * Returns the payload of the notification tap that launched the app
   * from a terminated state, or `null` if the app was opened any other
   * way (launcher, deep link, ...).
   */
  fun getInitialPayload(): Map<String, String>?

  companion object {
    /** The codec used by LocalNotificationHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      LocalNotificationPigeonCodec()
    }
    /** Sets up an instance of `LocalNotificationHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: LocalNotificationHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_lab.LocalNotificationHostApi.show$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val titleArg = args[0] as String
            val bodyArg = args[1] as String
            val payloadArg = args[2] as Map<String, String>
            val wrapped: List<Any?> = try {
              api.show(titleArg, bodyArg, payloadArg)
              listOf(null)
            } catch (exception: Throwable) {
              LocalNotificationPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_lab.LocalNotificationHostApi.getInitialPayload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getInitialPayload())
            } catch (exception: Throwable) {
              LocalNotificationPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Pigeon Flutter API for local notification events (native → Dart).
 *
 * Implemented on the Dart side and called from MainActivity when the
 * user taps a notification while the app process is alive (foreground
 * or background), which arrives as onNewIntent instead of a fresh
 * launch.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class LocalNotificationFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by LocalNotificationFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      LocalNotificationPigeonCodec()
    }
  }
  /** Delivers the payload of a tapped notification. */
  fun onNotificationTap(payloadArg: Map<String, String>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_lab.LocalNotificationFlutterApi.onNotificationTap$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(payloadArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LocalNotificationPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
