// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class GreetingApiPigeonCodecReader: FlutterStandardReader {
}

private class GreetingApiPigeonCodecWriter: FlutterStandardWriter {
}

private class GreetingApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return GreetingApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return GreetingApiPigeonCodecWriter(data: data)
  }
}

class GreetingApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = GreetingApiPigeonCodec(readerWriter: GreetingApiPigeonCodecReaderWriter())
}

/// Type-safe Pigeon API for greeting messages.
///
/// The native host returns `"Hello, {name}!"` for a given name.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol GreetingApi {
  /// Returns a greeting message for the given [name].
  func greet(name: String) throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class GreetingApiSetup {
  static var codec: FlutterStandardMessageCodec { GreetingApiPigeonCodec.shared }
  /// Sets up an instance of `GreetingApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: GreetingApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Returns a greeting message for the given [name].
    let greetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_lab.GreetingApi.greet\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      greetChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg = args[0] as! String
        do {
          let result = try api.greet(name: nameArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      greetChannel.setMessageHandler(nil)
    }
  }
}
