import 'package:flutter_lab/routing/routes.dart';

/// Identifier for every screen reachable in the app.
///
/// Each value carries its [path], which is the same string declared as a
/// constant in [Routes]. The enum exists so that screen-level policies
/// (such as which membership states can access a screen) can be expressed
/// as exhaustive switches.
enum Screen {
  home(Routes.home),
  login(Routes.login),
  loggedInHome(Routes.loggedInHome),
  loggedInHomeTab1(Routes.loggedInHomeTab1),
  loggedInHomeTab2(Routes.loggedInHomeTab2),
  notFound(Routes.notFound),
  webView(Routes.webView),
  launchUrl(Routes.launchUrl),
  launchUrlDetail(Routes.launchUrlDetail),
  portal(Routes.portal),
  sharedPreferences(Routes.sharedPreferences),
  s3EtagCache(Routes.s3EtagCache),
  appLifecycle(Routes.appLifecycle),
  localPaths(Routes.localPaths),
  localIcon(Routes.localIcon),
  urlNavigation(Routes.urlNavigation),
  dioCache(Routes.dioCache),
  etagCache(Routes.etagCache),
  pushNotification(Routes.pushNotification),
  appStore(Routes.appStore),
  network(Routes.network),
  brightness(Routes.brightness),
  inAppReview(Routes.inAppReview),
  screenshotPrevention(Routes.screenshotPrevention),
  ocr(Routes.ocr),
  ocrResult(Routes.ocrResult),
  loading(Routes.loading),
  loadingSubmit(Routes.loadingSubmit),
  formBuilder(Routes.formBuilder),
  permission(Routes.permission),
  popScope(Routes.popScope),
  autoMapprDemo(Routes.autoMapprDemo),
  effectVsListen(Routes.effectVsListen),
  methodChannel(Routes.methodChannel),
  asyncStateRace(Routes.asyncStateRace),
  googleApi(Routes.googleApi),
  pigeon(Routes.pigeon),
  dialogState(Routes.dialogState),
  observerDemo(Routes.observerDemo),
  observerDemoDetail(Routes.observerDemoDetail),
  routeAwareDemo(Routes.routeAwareDemo),
  routeAwareDemoDetail(Routes.routeAwareDemoDetail),
  currentRouteState(Routes.currentRouteState),
  navigationScreenA(Routes.navigationScreenA),
  navigationScreenB(Routes.navigationScreenB),
  navigationScreenC(Routes.navigationScreenC),
  clock(Routes.clock),
  counter(Routes.counter),
  deviceInfo(Routes.deviceInfo),
  horizontalLayout(Routes.horizontalLayout),
  nestedButton(Routes.nestedButton),
  markupSample(Routes.markupSample),
  imageProcessing(Routes.imageProcessing),
  camera(Routes.camera),
  routing(Routes.routing),
  routingCupertino(Routes.routingCupertino),
  routingCupertinoFullscreenDialog(Routes.routingCupertinoFullscreenDialog),
  petCache(Routes.petCache),
  arutana(Routes.arutana),
  max(Routes.max),
  adfurikun(Routes.adfurikun),
  profilePassport(Routes.profilePassport),
  animatedSwitcher(Routes.animatedSwitcher),
  analytics(Routes.analytics),
  crashlytics(Routes.crashlytics),
  firebasePerformance(Routes.firebasePerformance),
  shellDemo(Routes.shellDemo),
  shellDemoTab1(Routes.shellDemoTab1),
  shellDemoTab2(Routes.shellDemoTab2),
  shellDemoDetail(Routes.shellDemoDetail),
  shellDemoSub(Routes.shellDemoSub),
  tutorial(Routes.tutorial),
  scrollToSection(Routes.scrollToSection),
  visibilityDetector(Routes.visibilityDetector),
  streamSubscription(Routes.streamSubscription),
  webViewTabs(Routes.webViewTabs),
  webViewJavascript(Routes.webViewJavascript),
  webviewCookie(Routes.webviewCookie),
  httpOnlyCookie(Routes.httpOnlyCookie),
  webViewRemoteUrl(Routes.webViewRemoteUrl),
  adjustDeferredDeeplink(Routes.adjustDeferredDeeplink),
  talkerLogs(Routes.talkerLogs),
  errorHandling(Routes.errorHandling),
  tarDownload(Routes.tarDownload),
  ossLicenses(Routes.ossLicenses),
  debug(Routes.debug)
  ;

  const Screen(this.path);

  /// The GoRouter path string for this screen.
  final String path;
}
