// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class ArutanaPigeonCodecReader: FlutterStandardReader {
}

private class ArutanaPigeonCodecWriter: FlutterStandardWriter {
}

private class ArutanaPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ArutanaPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ArutanaPigeonCodecWriter(data: data)
  }
}

class ArutanaPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ArutanaPigeonCodec(readerWriter: ArutanaPigeonCodecReaderWriter())
}

/// Pigeon host API for Arutana ad SDK integration.
///
/// Provides methods to initialize interstitial and movie ads
/// via the native Arutana SDK.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ArutanaHostApi {
  /// Initializes an interstitial ad via the Arutana SDK.
  func initializeInterstitialAd() throws
  /// Initializes a movie ad via the Arutana SDK.
  func initializeMovieAd() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ArutanaHostApiSetup {
  static var codec: FlutterStandardMessageCodec { ArutanaPigeonCodec.shared }
  /// Sets up an instance of `ArutanaHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ArutanaHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Initializes an interstitial ad via the Arutana SDK.
    let initializeInterstitialAdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_lab.ArutanaHostApi.initializeInterstitialAd\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeInterstitialAdChannel.setMessageHandler { _, reply in
        do {
          try api.initializeInterstitialAd()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeInterstitialAdChannel.setMessageHandler(nil)
    }
    /// Initializes a movie ad via the Arutana SDK.
    let initializeMovieAdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_lab.ArutanaHostApi.initializeMovieAd\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeMovieAdChannel.setMessageHandler { _, reply in
        do {
          try api.initializeMovieAd()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeMovieAdChannel.setMessageHandler(nil)
    }
  }
}
