// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class PassKitPigeonCodecReader: FlutterStandardReader {
}

private class PassKitPigeonCodecWriter: FlutterStandardWriter {
}

private class PassKitPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PassKitPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PassKitPigeonCodecWriter(data: data)
  }
}

class PassKitPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PassKitPigeonCodec(readerWriter: PassKitPigeonCodecReaderWriter())
}

/// Pigeon host API for Apple Wallet (PassKit) integration.
///
/// Provides methods to check pass availability on iOS.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PassKitHostApi {
  /// Returns whether the specified pass can be added to Apple Wallet.
  ///
  /// Checks if the device supports adding passes and the pass
  /// with the given [passTypeIdentifier] and [serialNumber]
  /// is not already in the wallet.
  func canAddPass(passTypeIdentifier: String, serialNumber: String) throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PassKitHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PassKitPigeonCodec.shared }
  /// Sets up an instance of `PassKitHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PassKitHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Returns whether the specified pass can be added to Apple Wallet.
    ///
    /// Checks if the device supports adding passes and the pass
    /// with the given [passTypeIdentifier] and [serialNumber]
    /// is not already in the wallet.
    let canAddPassChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_lab.PassKitHostApi.canAddPass\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      canAddPassChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let passTypeIdentifierArg = args[0] as! String
        let serialNumberArg = args[1] as! String
        do {
          let result = try api.canAddPass(passTypeIdentifier: passTypeIdentifierArg, serialNumber: serialNumberArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      canAddPassChannel.setMessageHandler(nil)
    }
  }
}
