// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class ProfilePassportPigeonCodecReader: FlutterStandardReader {
}

private class ProfilePassportPigeonCodecWriter: FlutterStandardWriter {
}

private class ProfilePassportPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ProfilePassportPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ProfilePassportPigeonCodecWriter(data: data)
  }
}

class ProfilePassportPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ProfilePassportPigeonCodec(readerWriter: ProfilePassportPigeonCodecReaderWriter())
}


/// Pigeon host API for ProfilePassport SDK integration.
///
/// Provides methods to start the PPSDK service
/// via the native ProfilePassport SDK.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ProfilePassportHostApi {
  /// Starts the PPSDK service.
  func startService(completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ProfilePassportHostApiSetup {
  static var codec: FlutterStandardMessageCodec { ProfilePassportPigeonCodec.shared }
  /// Sets up an instance of `ProfilePassportHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ProfilePassportHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Starts the PPSDK service.
    let startServiceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_lab.ProfilePassportHostApi.startService\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startServiceChannel.setMessageHandler { _, reply in
        api.startService { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startServiceChannel.setMessageHandler(nil)
    }
  }
}
